name: Build Android APK

on:
  workflow_dispatch: # Allows manual triggering from GitHub Actions tab
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Web App
        run: npm run build

      - name: Setup Capacitor & Android
        run: |
          # Install Capacitor dependencies locally for this build
          npm install @capacitor/core @capacitor/cli @capacitor/android
          
          # Initialize Capacitor Project
          npx cap init "SNES Mobile" "com.retropocket.snes" --web-dir dist --npm-client npm
          
          # Add Android Platform
          npx cap add android

          # Sync config
          npx cap sync android

      - name: Build Android APK (Debug)
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: snes-mobile-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
